#!/usr/bin/env bash
#
# Regenerates the source-build formula in katbyte/homebrew-tap for a released tag.
# Usage: TAG=v1.0.0 [TAP_DRY_RUN=1] HOMEBREW_TAP_GITHUB_TOKEN=... ./scripts/update-homebrew-formula.sh
set -euo pipefail

TAG="${TAG:?set TAG to the release tag, e.g. v1.0.0}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "==> fetching source tarball for ${TAG}..."
curl -sSfL "https://github.com/katbyte/prowlarr-mcp/archive/refs/tags/${TAG}.tar.gz" -o "$tmp/src.tar.gz"
SHA256="$(sha256sum "$tmp/src.tar.gz" | cut -d' ' -f1)"

cat > "$tmp/prowlarr-mcp.rb" <<FORMULA
# typed: false
# frozen_string_literal: true

# This file is generated by the prowlarr-mcp release workflow - do not edit by hand.
class ProwlarrMcp < Formula
  desc "MCP server and CLI for auditing and running a Prowlarr indexer manager"
  homepage "https://github.com/katbyte/prowlarr-mcp"
  url "https://github.com/katbyte/prowlarr-mcp/archive/refs/tags/${TAG}.tar.gz"
  sha256 "${SHA256}"
  license "GPL-3.0-only"
  head "https://github.com/katbyte/prowlarr-mcp.git", branch: "main"

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/katbyte/go-kt/version.Version=${TAG} -X github.com/katbyte/go-kt/version.GitCommit=homebrew")
  end

  test do
    assert_match "${TAG}", shell_output("#{bin}/prowlarr-mcp version")
  end
end
FORMULA

if [ "${TAP_DRY_RUN:-0}" = "1" ]; then
  echo "==> dry run; generated formula:"
  cat "$tmp/prowlarr-mcp.rb"
  exit 0
fi

: "${HOMEBREW_TAP_GITHUB_TOKEN:?set HOMEBREW_TAP_GITHUB_TOKEN to a token with push access to katbyte/homebrew-tap}"
echo "==> pushing formula to katbyte/homebrew-tap..."
git clone --depth 1 "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/katbyte/homebrew-tap.git" "$tmp/tap"
mkdir -p "$tmp/tap/Formula"
cp "$tmp/prowlarr-mcp.rb" "$tmp/tap/Formula/prowlarr-mcp.rb"
cd "$tmp/tap"
git config user.name "prowlarr-mcp-release"
git config user.email "prowlarr-mcp-release@katbyte.me"
git add Formula/prowlarr-mcp.rb
git diff --cached --quiet && { echo "==> formula unchanged"; exit 0; }
git commit -m "prowlarr-mcp ${TAG}"
git push
echo "==> done"
