// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// ApiInfoResource is the "ApiInfoResource" schema.
type ApiInfoResource struct {
	Current    string   `json:"current,omitempty"`
	Deprecated []string `json:"deprecated,omitzero"`
}
