// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// ApplicationBulkResource is the "ApplicationBulkResource" schema.
type ApplicationBulkResource struct {
	ApplyTags ApplyTags            `json:"applyTags,omitempty"`
	Ids       []int                `json:"ids,omitzero"`
	SyncLevel ApplicationSyncLevel `json:"syncLevel,omitempty"`
	Tags      []int                `json:"tags,omitzero"`
}
