// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PutApplicationsByIdOperationResponse is the result of PutApplicationsById.
type PutApplicationsByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ApplicationResource
}

// PutApplicationsByIdOperationOptions holds the query and header parameters of PutApplicationsById.
type PutApplicationsByIdOperationOptions struct {
	ForceSave *bool
}

// ToHeaders returns the header parameters the options set.
func (o PutApplicationsByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutApplicationsByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceSave != nil {
		out.Append("forceSave", strconv.FormatBool(*o.ForceSave))
	}
	return &out
}

// PutApplicationsById calls PUT /api/v1/applications/{id}.
func (c Client) PutApplicationsById(ctx context.Context, id int, input ApplicationResource, options PutApplicationsByIdOperationOptions) (result PutApplicationsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v1/applications/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ApplicationResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
