// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// DeleteApplicationsBulkOperationResponse is the result of DeleteApplicationsBulk.
type DeleteApplicationsBulkOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteApplicationsBulk calls DELETE /api/v1/applications/bulk.
func (c Client) DeleteApplicationsBulk(ctx context.Context, input ApplicationBulkResource) (result DeleteApplicationsBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v1/applications/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
