// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// ApplicationResource is the "ApplicationResource" schema.
type ApplicationResource struct {
	ConfigContract     string                `json:"configContract,omitempty"`
	Fields             []Field               `json:"fields,omitzero"`
	Id                 int                   `json:"id,omitempty"`
	Implementation     string                `json:"implementation,omitempty"`
	ImplementationName string                `json:"implementationName,omitempty"`
	InfoLink           string                `json:"infoLink,omitempty"`
	Message            *ProviderMessage      `json:"message,omitempty"`
	Name               string                `json:"name,omitempty"`
	Presets            []ApplicationResource `json:"presets,omitzero"`
	SyncLevel          ApplicationSyncLevel  `json:"syncLevel,omitempty"`
	Tags               []int                 `json:"tags,omitzero"`
	TestCommand        string                `json:"testCommand,omitempty"`
}
