// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PostApplicationsTestOperationResponse is the result of PostApplicationsTest.
type PostApplicationsTestOperationResponse struct {
	HttpResponse *http.Response
}

// PostApplicationsTestOperationOptions holds the query and header parameters of PostApplicationsTest.
type PostApplicationsTestOperationOptions struct {
	ForceTest *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostApplicationsTestOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostApplicationsTestOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceTest != nil {
		out.Append("forceTest", strconv.FormatBool(*o.ForceTest))
	}
	return &out
}

// PostApplicationsTest calls POST /api/v1/applications/test.
func (c Client) PostApplicationsTest(ctx context.Context, input ApplicationResource, options PostApplicationsTestOperationOptions) (result PostApplicationsTestOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v1/applications/test",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
