// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetApplicationsSchemaOperationResponse is the result of GetApplicationsSchema.
type GetApplicationsSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        []ApplicationResource
}

// GetApplicationsSchema calls GET /api/v1/applications/schema.
func (c Client) GetApplicationsSchema(ctx context.Context) (result GetApplicationsSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/applications/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
