// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// ApplicationSyncLevel is the "ApplicationSyncLevel" enum.
type ApplicationSyncLevel string

// Values of ApplicationSyncLevel.
const (
	ApplicationSyncLevelDisabled ApplicationSyncLevel = "disabled"
	ApplicationSyncLevelAddOnly  ApplicationSyncLevel = "addOnly"
	ApplicationSyncLevelFullSync ApplicationSyncLevel = "fullSync"
)

// PossibleValuesForApplicationSyncLevel returns every value of ApplicationSyncLevel.
func PossibleValuesForApplicationSyncLevel() []string {
	return []string{
		string(ApplicationSyncLevelDisabled),
		string(ApplicationSyncLevelAddOnly),
		string(ApplicationSyncLevelFullSync),
	}
}
