// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PutApplicationsBulkOperationResponse is the result of PutApplicationsBulk.
type PutApplicationsBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        []ApplicationResource
}

// PutApplicationsBulk calls PUT /api/v1/applications/bulk.
func (c Client) PutApplicationsBulk(ctx context.Context, input ApplicationBulkResource) (result PutApplicationsBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v1/applications/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
