// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetApplicationsByIdOperationResponse is the result of GetApplicationsById.
type GetApplicationsByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ApplicationResource
}

// GetApplicationsById calls GET /api/v1/applications/{id}.
func (c Client) GetApplicationsById(ctx context.Context, id int) (result GetApplicationsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v1/applications/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ApplicationResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
