// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetAppProfileOperationResponse is the result of GetAppProfile.
type GetAppProfileOperationResponse struct {
	HttpResponse *http.Response
	Model        []AppProfileResource
}

// GetAppProfile calls GET /api/v1/appprofile.
func (c Client) GetAppProfile(ctx context.Context) (result GetAppProfileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/appprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
