// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetAppProfileSchemaOperationResponse is the result of GetAppProfileSchema.
type GetAppProfileSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        *AppProfileResource
}

// GetAppProfileSchema calls GET /api/v1/appprofile/schema.
func (c Client) GetAppProfileSchema(ctx context.Context) (result GetAppProfileSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/appprofile/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AppProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
