// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetAppProfileByIdOperationResponse is the result of GetAppProfileById.
type GetAppProfileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *AppProfileResource
}

// GetAppProfileById calls GET /api/v1/appprofile/{id}.
func (c Client) GetAppProfileById(ctx context.Context, id int) (result GetAppProfileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v1/appprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AppProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
