// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// AppProfileResource is the "AppProfileResource" schema.
type AppProfileResource struct {
	EnableAutomaticSearch   *bool  `json:"enableAutomaticSearch,omitempty"`
	EnableInteractiveSearch *bool  `json:"enableInteractiveSearch,omitempty"`
	EnableRss               *bool  `json:"enableRss,omitempty"`
	Id                      int    `json:"id,omitempty"`
	MinimumSeeders          int    `json:"minimumSeeders,omitempty"`
	Name                    string `json:"name,omitempty"`
}
