// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// DeleteSystemBackupByIdOperationResponse is the result of DeleteSystemBackupById.
type DeleteSystemBackupByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteSystemBackupById calls DELETE /api/v1/system/backup/{id}.
func (c Client) DeleteSystemBackupById(ctx context.Context, id int) (result DeleteSystemBackupByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v1/system/backup/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
