// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// ApplyTags is the "ApplyTags" enum.
type ApplyTags string

// Values of ApplyTags.
const (
	ApplyTagsAdd     ApplyTags = "add"
	ApplyTagsRemove  ApplyTags = "remove"
	ApplyTagsReplace ApplyTags = "replace"
)

// PossibleValuesForApplyTags returns every value of ApplyTags.
func PossibleValuesForApplyTags() []string {
	return []string{
		string(ApplyTagsAdd),
		string(ApplyTagsRemove),
		string(ApplyTagsReplace),
	}
}

// AuthenticationType is the "AuthenticationType" enum.
type AuthenticationType string

// Values of AuthenticationType.
const (
	AuthenticationTypeNone     AuthenticationType = "none"
	AuthenticationTypeBasic    AuthenticationType = "basic"
	AuthenticationTypeForms    AuthenticationType = "forms"
	AuthenticationTypeExternal AuthenticationType = "external"
)

// PossibleValuesForAuthenticationType returns every value of AuthenticationType.
func PossibleValuesForAuthenticationType() []string {
	return []string{
		string(AuthenticationTypeNone),
		string(AuthenticationTypeBasic),
		string(AuthenticationTypeForms),
		string(AuthenticationTypeExternal),
	}
}

// DownloadProtocol is the "DownloadProtocol" enum.
type DownloadProtocol string

// Values of DownloadProtocol.
const (
	DownloadProtocolUnknown DownloadProtocol = "unknown"
	DownloadProtocolUsenet  DownloadProtocol = "usenet"
	DownloadProtocolTorrent DownloadProtocol = "torrent"
)

// PossibleValuesForDownloadProtocol returns every value of DownloadProtocol.
func PossibleValuesForDownloadProtocol() []string {
	return []string{
		string(DownloadProtocolUnknown),
		string(DownloadProtocolUsenet),
		string(DownloadProtocolTorrent),
	}
}

// PrivacyLevel is the "PrivacyLevel" enum.
type PrivacyLevel string

// Values of PrivacyLevel.
const (
	PrivacyLevelNormal   PrivacyLevel = "normal"
	PrivacyLevelPassword PrivacyLevel = "password"
	PrivacyLevelApiKey   PrivacyLevel = "apiKey"
	PrivacyLevelUserName PrivacyLevel = "userName"
)

// PossibleValuesForPrivacyLevel returns every value of PrivacyLevel.
func PossibleValuesForPrivacyLevel() []string {
	return []string{
		string(PrivacyLevelNormal),
		string(PrivacyLevelPassword),
		string(PrivacyLevelApiKey),
		string(PrivacyLevelUserName),
	}
}

// ProviderMessageType is the "ProviderMessageType" enum.
type ProviderMessageType string

// Values of ProviderMessageType.
const (
	ProviderMessageTypeInfo    ProviderMessageType = "info"
	ProviderMessageTypeWarning ProviderMessageType = "warning"
	ProviderMessageTypeError   ProviderMessageType = "error"
)

// PossibleValuesForProviderMessageType returns every value of ProviderMessageType.
func PossibleValuesForProviderMessageType() []string {
	return []string{
		string(ProviderMessageTypeInfo),
		string(ProviderMessageTypeWarning),
		string(ProviderMessageTypeError),
	}
}

// SortDirection is the "SortDirection" enum.
type SortDirection string

// Values of SortDirection.
const (
	SortDirectionDefault    SortDirection = "default"
	SortDirectionAscending  SortDirection = "ascending"
	SortDirectionDescending SortDirection = "descending"
)

// PossibleValuesForSortDirection returns every value of SortDirection.
func PossibleValuesForSortDirection() []string {
	return []string{
		string(SortDirectionDefault),
		string(SortDirectionAscending),
		string(SortDirectionDescending),
	}
}

// UpdateMechanism is the "UpdateMechanism" enum.
type UpdateMechanism string

// Values of UpdateMechanism.
const (
	UpdateMechanismBuiltIn  UpdateMechanism = "builtIn"
	UpdateMechanismScript   UpdateMechanism = "script"
	UpdateMechanismExternal UpdateMechanism = "external"
	UpdateMechanismApt      UpdateMechanism = "apt"
	UpdateMechanismDocker   UpdateMechanism = "docker"
)

// PossibleValuesForUpdateMechanism returns every value of UpdateMechanism.
func PossibleValuesForUpdateMechanism() []string {
	return []string{
		string(UpdateMechanismBuiltIn),
		string(UpdateMechanismScript),
		string(UpdateMechanismExternal),
		string(UpdateMechanismApt),
		string(UpdateMechanismDocker),
	}
}
