// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// IndexerStatusResource is the "IndexerStatusResource" schema.
type IndexerStatusResource struct {
	DisabledTill      string `json:"disabledTill,omitempty"`
	Id                int    `json:"id,omitempty"`
	IndexerId         int    `json:"indexerId,omitempty"`
	InitialFailure    string `json:"initialFailure,omitempty"`
	MostRecentFailure string `json:"mostRecentFailure,omitempty"`
}
