// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// SelectOption is the "SelectOption" schema.
type SelectOption struct {
	Hint        string `json:"hint,omitempty"`
	Name        string `json:"name,omitempty"`
	Order       int    `json:"order,omitempty"`
	ParentValue int    `json:"parentValue,omitempty"`
	Value       int    `json:"value,omitempty"`
}
