// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// IndexerCategory is the "IndexerCategory" schema.
type IndexerCategory struct {
	Description   string            `json:"description,omitempty"`
	Id            int               `json:"id,omitempty"`
	Name          string            `json:"name,omitempty"`
	SubCategories []IndexerCategory `json:"subCategories,omitzero"`
}
