// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetConfigDevelopmentOperationResponse is the result of GetConfigDevelopment.
type GetConfigDevelopmentOperationResponse struct {
	HttpResponse *http.Response
	Model        *DevelopmentConfigResource
}

// GetConfigDevelopment calls GET /api/v1/config/development.
func (c Client) GetConfigDevelopment(ctx context.Context) (result GetConfigDevelopmentOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/config/development",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DevelopmentConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
