// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetConfigDevelopmentByIdOperationResponse is the result of GetConfigDevelopmentById.
type GetConfigDevelopmentByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DevelopmentConfigResource
}

// GetConfigDevelopmentById calls GET /api/v1/config/development/{id}.
func (c Client) GetConfigDevelopmentById(ctx context.Context, id int) (result GetConfigDevelopmentByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v1/config/development/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DevelopmentConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
