// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// DevelopmentConfigResource is the "DevelopmentConfigResource" schema.
type DevelopmentConfigResource struct {
	ConsoleLogLevel    string `json:"consoleLogLevel"`
	FilterSentryEvents *bool  `json:"filterSentryEvents,omitempty"`
	Id                 int    `json:"id"`
	LogIndexerResponse *bool  `json:"logIndexerResponse,omitempty"`
	LogRotate          int    `json:"logRotate"`
	LogSql             *bool  `json:"logSql,omitempty"`
}
