// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PutConfigDevelopmentByIdOperationResponse is the result of PutConfigDevelopmentById.
type PutConfigDevelopmentByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DevelopmentConfigResource
}

// PutConfigDevelopmentById calls PUT /api/v1/config/development/{id}.
func (c Client) PutConfigDevelopmentById(ctx context.Context, id int, input DevelopmentConfigResource) (result PutConfigDevelopmentByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v1/config/development/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DevelopmentConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
