// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetDownloadClientOperationResponse is the result of GetDownloadClient.
type GetDownloadClientOperationResponse struct {
	HttpResponse *http.Response
	Model        []DownloadClientResource
}

// GetDownloadClient calls GET /api/v1/downloadclient.
func (c Client) GetDownloadClient(ctx context.Context) (result GetDownloadClientOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/downloadclient",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
