// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PostDownloadClientTestAllOperationResponse is the result of PostDownloadClientTestAll.
type PostDownloadClientTestAllOperationResponse struct {
	HttpResponse *http.Response
	Model        []ProviderTestAllResult
}

// PostDownloadClientTestAll calls POST /api/v1/downloadclient/testall.
func (c Client) PostDownloadClientTestAll(ctx context.Context) (result PostDownloadClientTestAllOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusBadRequest,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v1/downloadclient/testall",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
