// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// DownloadClientResource is the "DownloadClientResource" schema.
type DownloadClientResource struct {
	Categories         []DownloadClientCategory `json:"categories,omitzero"`
	ConfigContract     string                   `json:"configContract,omitempty"`
	Enable             *bool                    `json:"enable,omitempty"`
	Fields             []Field                  `json:"fields,omitzero"`
	Id                 int                      `json:"id,omitempty"`
	Implementation     string                   `json:"implementation,omitempty"`
	ImplementationName string                   `json:"implementationName,omitempty"`
	InfoLink           string                   `json:"infoLink,omitempty"`
	Message            *ProviderMessage         `json:"message,omitempty"`
	Name               string                   `json:"name,omitempty"`
	Presets            []DownloadClientResource `json:"presets,omitzero"`
	Priority           int                      `json:"priority,omitempty"`
	Protocol           DownloadProtocol         `json:"protocol,omitempty"`
	SupportsCategories *bool                    `json:"supportsCategories,omitempty"`
	Tags               []int                    `json:"tags,omitzero"`
}
