// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// DownloadClientCategory is the "DownloadClientCategory" schema.
type DownloadClientCategory struct {
	Categories     []int  `json:"categories,omitzero"`
	ClientCategory string `json:"clientCategory,omitempty"`
}
