// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// DownloadClientConfigResource is the "DownloadClientConfigResource" schema.
type DownloadClientConfigResource struct {
	Id int `json:"id"`
}
