// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetHistoryOperationResponse is the result of GetHistory.
type GetHistoryOperationResponse struct {
	HttpResponse *http.Response
	Model        *HistoryResourcePagingResource
}

// GetHistoryOperationOptions holds the query and header parameters of GetHistory.
type GetHistoryOperationOptions struct {
	Page          int
	PageSize      int
	SortKey       string
	SortDirection SortDirection
	EventType     []int
	Successful    *bool
	DownloadId    string
	IndexerIds    []int
}

// ToHeaders returns the header parameters the options set.
func (o GetHistoryOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetHistoryOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Page != 0 {
		out.Append("page", strconv.Itoa(o.Page))
	}
	if o.PageSize != 0 {
		out.Append("pageSize", strconv.Itoa(o.PageSize))
	}
	if o.SortKey != "" {
		out.Append("sortKey", o.SortKey)
	}
	if o.SortDirection != "" {
		out.Append("sortDirection", string(o.SortDirection))
	}
	for _, v := range o.EventType {
		out.Append("eventType", strconv.Itoa(v))
	}
	if o.Successful != nil {
		out.Append("successful", strconv.FormatBool(*o.Successful))
	}
	if o.DownloadId != "" {
		out.Append("downloadId", o.DownloadId)
	}
	for _, v := range o.IndexerIds {
		out.Append("indexerIds", strconv.Itoa(v))
	}
	return &out
}

// GetHistory calls GET /api/v1/history.
func (c Client) GetHistory(ctx context.Context, options GetHistoryOperationOptions) (result GetHistoryOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v1/history",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model HistoryResourcePagingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetHistoryCompleteResult is every result GetHistoryComplete loaded.
type GetHistoryCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []HistoryResource
}

// GetHistoryComplete calls GetHistory page by page, from options.Page (the first page
// when unset), until every result is loaded. options.PageSize is the page size,
// client.DefaultPageSize when unset.
func (c Client) GetHistoryComplete(ctx context.Context, options GetHistoryOperationOptions) (result GetHistoryCompleteResult, err error) {
	if options.PageSize <= 0 {
		options.PageSize = client.DefaultPageSize
	}
	if options.Page <= 0 {
		options.Page = 1
	}
	for {
		var page GetHistoryOperationResponse
		page, err = c.GetHistory(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Records) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Records...)
		// a short page is the last; so is the page that reaches the total
		if len(page.Model.Records) < options.PageSize || page.Model.TotalRecords > 0 && options.Page*options.PageSize >= page.Model.TotalRecords {
			return
		}
		options.Page++
	}
}
