// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetHistoryIndexerOperationResponse is the result of GetHistoryIndexer.
type GetHistoryIndexerOperationResponse struct {
	HttpResponse *http.Response
	Model        []HistoryResource
}

// GetHistoryIndexerOperationOptions holds the query and header parameters of GetHistoryIndexer.
type GetHistoryIndexerOperationOptions struct {
	IndexerId int
	EventType HistoryEventType
	Limit     int
}

// ToHeaders returns the header parameters the options set.
func (o GetHistoryIndexerOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetHistoryIndexerOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IndexerId != 0 {
		out.Append("indexerId", strconv.Itoa(o.IndexerId))
	}
	if o.EventType != "" {
		out.Append("eventType", string(o.EventType))
	}
	if o.Limit != 0 {
		out.Append("limit", strconv.Itoa(o.Limit))
	}
	return &out
}

// GetHistoryIndexer calls GET /api/v1/history/indexer.
func (c Client) GetHistoryIndexer(ctx context.Context, options GetHistoryIndexerOperationOptions) (result GetHistoryIndexerOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v1/history/indexer",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
