// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetHistorySinceOperationResponse is the result of GetHistorySince.
type GetHistorySinceOperationResponse struct {
	HttpResponse *http.Response
	Model        []HistoryResource
}

// GetHistorySinceOperationOptions holds the query and header parameters of GetHistorySince.
type GetHistorySinceOperationOptions struct {
	Date      string
	EventType HistoryEventType
}

// ToHeaders returns the header parameters the options set.
func (o GetHistorySinceOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetHistorySinceOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Date != "" {
		out.Append("date", o.Date)
	}
	if o.EventType != "" {
		out.Append("eventType", string(o.EventType))
	}
	return &out
}

// GetHistorySince calls GET /api/v1/history/since.
func (c Client) GetHistorySince(ctx context.Context, options GetHistorySinceOperationOptions) (result GetHistorySinceOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v1/history/since",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
