// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// HistoryEventType is the "HistoryEventType" enum.
type HistoryEventType string

// Values of HistoryEventType.
const (
	HistoryEventTypeUnknown        HistoryEventType = "unknown"
	HistoryEventTypeReleaseGrabbed HistoryEventType = "releaseGrabbed"
	HistoryEventTypeIndexerQuery   HistoryEventType = "indexerQuery"
	HistoryEventTypeIndexerRss     HistoryEventType = "indexerRss"
	HistoryEventTypeIndexerAuth    HistoryEventType = "indexerAuth"
	HistoryEventTypeIndexerInfo    HistoryEventType = "indexerInfo"
)

// PossibleValuesForHistoryEventType returns every value of HistoryEventType.
func PossibleValuesForHistoryEventType() []string {
	return []string{
		string(HistoryEventTypeUnknown),
		string(HistoryEventTypeReleaseGrabbed),
		string(HistoryEventTypeIndexerQuery),
		string(HistoryEventTypeIndexerRss),
		string(HistoryEventTypeIndexerAuth),
		string(HistoryEventTypeIndexerInfo),
	}
}
