// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// IndexerStatsResource is the "IndexerStatsResource" schema.
type IndexerStatsResource struct {
	Hosts      []HostStatistics      `json:"hosts,omitzero"`
	Id         int                   `json:"id,omitempty"`
	Indexers   []IndexerStatistics   `json:"indexers,omitzero"`
	UserAgents []UserAgentStatistics `json:"userAgents,omitzero"`
}
