// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// IndexerResource is the "IndexerResource" schema.
type IndexerResource struct {
	Added              string                     `json:"added,omitempty"`
	AppProfileId       int                        `json:"appProfileId,omitempty"`
	Capabilities       *IndexerCapabilityResource `json:"capabilities,omitempty"`
	ConfigContract     string                     `json:"configContract,omitempty"`
	DefinitionName     string                     `json:"definitionName,omitempty"`
	Description        string                     `json:"description,omitempty"`
	DownloadClientId   int                        `json:"downloadClientId,omitempty"`
	Enable             *bool                      `json:"enable,omitempty"`
	Encoding           string                     `json:"encoding,omitempty"`
	Fields             []Field                    `json:"fields,omitzero"`
	Id                 int                        `json:"id,omitempty"`
	Implementation     string                     `json:"implementation,omitempty"`
	ImplementationName string                     `json:"implementationName,omitempty"`
	IndexerUrls        []string                   `json:"indexerUrls,omitzero"`
	InfoLink           string                     `json:"infoLink,omitempty"`
	Language           string                     `json:"language,omitempty"`
	LegacyUrls         []string                   `json:"legacyUrls,omitzero"`
	Message            *ProviderMessage           `json:"message,omitempty"`
	Name               string                     `json:"name,omitempty"`
	Presets            []IndexerResource          `json:"presets,omitzero"`
	Priority           int                        `json:"priority,omitempty"`
	Privacy            IndexerPrivacy             `json:"privacy,omitempty"`
	Protocol           DownloadProtocol           `json:"protocol,omitempty"`
	Redirect           *bool                      `json:"redirect,omitempty"`
	SortName           string                     `json:"sortName,omitempty"`
	Status             *IndexerStatusResource     `json:"status,omitempty"`
	SupportsPagination *bool                      `json:"supportsPagination,omitempty"`
	SupportsRedirect   *bool                      `json:"supportsRedirect,omitempty"`
	SupportsRss        *bool                      `json:"supportsRss,omitempty"`
	SupportsSearch     *bool                      `json:"supportsSearch,omitempty"`
	Tags               []int                      `json:"tags,omitzero"`
}
