// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetIndexerStatsOperationResponse is the result of GetIndexerStats.
type GetIndexerStatsOperationResponse struct {
	HttpResponse *http.Response
	Model        *IndexerStatsResource
}

// GetIndexerStatsOperationOptions holds the query and header parameters of GetIndexerStats.
type GetIndexerStatsOperationOptions struct {
	StartDate string
	EndDate   string
	Indexers  string
	Protocols string
	Tags      string
}

// ToHeaders returns the header parameters the options set.
func (o GetIndexerStatsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetIndexerStatsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.StartDate != "" {
		out.Append("startDate", o.StartDate)
	}
	if o.EndDate != "" {
		out.Append("endDate", o.EndDate)
	}
	if o.Indexers != "" {
		out.Append("indexers", o.Indexers)
	}
	if o.Protocols != "" {
		out.Append("protocols", o.Protocols)
	}
	if o.Tags != "" {
		out.Append("tags", o.Tags)
	}
	return &out
}

// GetIndexerStats calls GET /api/v1/indexerstats.
func (c Client) GetIndexerStats(ctx context.Context, options GetIndexerStatsOperationOptions) (result GetIndexerStatsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v1/indexerstats",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model IndexerStatsResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
