// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PutIndexerProxyByIdOperationResponse is the result of PutIndexerProxyById.
type PutIndexerProxyByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *IndexerProxyResource
}

// PutIndexerProxyByIdOperationOptions holds the query and header parameters of PutIndexerProxyById.
type PutIndexerProxyByIdOperationOptions struct {
	ForceSave *bool
}

// ToHeaders returns the header parameters the options set.
func (o PutIndexerProxyByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutIndexerProxyByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceSave != nil {
		out.Append("forceSave", strconv.FormatBool(*o.ForceSave))
	}
	return &out
}

// PutIndexerProxyById calls PUT /api/v1/indexerproxy/{id}.
func (c Client) PutIndexerProxyById(ctx context.Context, id int, input IndexerProxyResource, options PutIndexerProxyByIdOperationOptions) (result PutIndexerProxyByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v1/indexerproxy/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model IndexerProxyResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
