// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PostIndexerProxyActionByNameOperationResponse is the result of PostIndexerProxyActionByName.
type PostIndexerProxyActionByNameOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// PostIndexerProxyActionByName calls POST /api/v1/indexerproxy/action/{name}.
func (c Client) PostIndexerProxyActionByName(ctx context.Context, name string, input IndexerProxyResource) (result PostIndexerProxyActionByNameOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/api/v1/indexerproxy/action/%s", url.PathEscape(name)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
