// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// UserAgentStatistics is the "UserAgentStatistics" schema.
type UserAgentStatistics struct {
	NumberOfGrabs   int    `json:"numberOfGrabs,omitempty"`
	NumberOfQueries int    `json:"numberOfQueries,omitempty"`
	UserAgent       string `json:"userAgent,omitempty"`
}
