// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

func TestOperationGetIndexerStats(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetIndexerStats(t.Context(), GetIndexerStatsOperationOptions{
		StartDate: "v-StartDate",
		EndDate:   "v-EndDate",
		Indexers:  "v-Indexers",
		Protocols: "v-Protocols",
		Tags:      "v-Tags",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v1/indexerstats")
	expectQuery(t, r, "startDate", "v-StartDate")
	expectQuery(t, r, "endDate", "v-EndDate")
	expectQuery(t, r, "indexers", "v-Indexers")
	expectQuery(t, r, "protocols", "v-Protocols")
	expectQuery(t, r, "tags", "v-Tags")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetIndexerStats(t.Context(), GetIndexerStatsOperationOptions{
		StartDate: "v-StartDate",
		EndDate:   "v-EndDate",
		Indexers:  "v-Indexers",
		Protocols: "v-Protocols",
		Tags:      "v-Tags",
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetIndexerStats(t.Context(), GetIndexerStatsOperationOptions{
		StartDate: "v-StartDate",
		EndDate:   "v-EndDate",
		Indexers:  "v-Indexers",
		Protocols: "v-Protocols",
		Tags:      "v-Tags",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
