// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// HostStatistics is the "HostStatistics" schema.
type HostStatistics struct {
	Host            string `json:"host,omitempty"`
	NumberOfGrabs   int    `json:"numberOfGrabs,omitempty"`
	NumberOfQueries int    `json:"numberOfQueries,omitempty"`
}
