// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// IndexerCapabilityResource is the "IndexerCapabilityResource" schema.
type IndexerCapabilityResource struct {
	BookSearchParams  []BookSearchParam  `json:"bookSearchParams,omitzero"`
	Categories        []IndexerCategory  `json:"categories,omitzero"`
	Id                int                `json:"id,omitempty"`
	LimitsDefault     int                `json:"limitsDefault,omitempty"`
	LimitsMax         int                `json:"limitsMax,omitempty"`
	MovieSearchParams []MovieSearchParam `json:"movieSearchParams,omitzero"`
	MusicSearchParams []MusicSearchParam `json:"musicSearchParams,omitzero"`
	SearchParams      []SearchParam      `json:"searchParams,omitzero"`
	SupportsRawSearch *bool              `json:"supportsRawSearch,omitempty"`
	TvSearchParams    []TvSearchParam    `json:"tvSearchParams,omitzero"`
}
