// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// IndexerProxyResource is the "IndexerProxyResource" schema.
type IndexerProxyResource struct {
	ConfigContract        string                 `json:"configContract,omitempty"`
	Fields                []Field                `json:"fields,omitzero"`
	Id                    int                    `json:"id,omitempty"`
	Implementation        string                 `json:"implementation,omitempty"`
	ImplementationName    string                 `json:"implementationName,omitempty"`
	IncludeHealthWarnings *bool                  `json:"includeHealthWarnings,omitempty"`
	InfoLink              string                 `json:"infoLink,omitempty"`
	Link                  string                 `json:"link,omitempty"`
	Message               *ProviderMessage       `json:"message,omitempty"`
	Name                  string                 `json:"name,omitempty"`
	OnHealthIssue         *bool                  `json:"onHealthIssue,omitempty"`
	Presets               []IndexerProxyResource `json:"presets,omitzero"`
	SupportsOnHealthIssue *bool                  `json:"supportsOnHealthIssue,omitempty"`
	Tags                  []int                  `json:"tags,omitzero"`
	TestCommand           string                 `json:"testCommand,omitempty"`
}
