// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetIndexerCategoriesOperationResponse is the result of GetIndexerCategories.
type GetIndexerCategoriesOperationResponse struct {
	HttpResponse *http.Response
	Model        []IndexerCategory
}

// GetIndexerCategories calls GET /api/v1/indexer/categories.
func (c Client) GetIndexerCategories(ctx context.Context) (result GetIndexerCategoriesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/indexer/categories",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
