// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// BookSearchParam is the "BookSearchParam" enum.
type BookSearchParam string

// Values of BookSearchParam.
const (
	BookSearchParamQ         BookSearchParam = "q"
	BookSearchParamTitle     BookSearchParam = "title"
	BookSearchParamAuthor    BookSearchParam = "author"
	BookSearchParamPublisher BookSearchParam = "publisher"
	BookSearchParamGenre     BookSearchParam = "genre"
	BookSearchParamYear      BookSearchParam = "year"
)

// PossibleValuesForBookSearchParam returns every value of BookSearchParam.
func PossibleValuesForBookSearchParam() []string {
	return []string{
		string(BookSearchParamQ),
		string(BookSearchParamTitle),
		string(BookSearchParamAuthor),
		string(BookSearchParamPublisher),
		string(BookSearchParamGenre),
		string(BookSearchParamYear),
	}
}

// IndexerPrivacy is the "IndexerPrivacy" enum.
type IndexerPrivacy string

// Values of IndexerPrivacy.
const (
	IndexerPrivacyPublic      IndexerPrivacy = "public"
	IndexerPrivacySemiPrivate IndexerPrivacy = "semiPrivate"
	IndexerPrivacyPrivate     IndexerPrivacy = "private"
)

// PossibleValuesForIndexerPrivacy returns every value of IndexerPrivacy.
func PossibleValuesForIndexerPrivacy() []string {
	return []string{
		string(IndexerPrivacyPublic),
		string(IndexerPrivacySemiPrivate),
		string(IndexerPrivacyPrivate),
	}
}

// MovieSearchParam is the "MovieSearchParam" enum.
type MovieSearchParam string

// Values of MovieSearchParam.
const (
	MovieSearchParamQ         MovieSearchParam = "q"
	MovieSearchParamImdbId    MovieSearchParam = "imdbId"
	MovieSearchParamTmdbId    MovieSearchParam = "tmdbId"
	MovieSearchParamImdbTitle MovieSearchParam = "imdbTitle"
	MovieSearchParamImdbYear  MovieSearchParam = "imdbYear"
	MovieSearchParamTraktId   MovieSearchParam = "traktId"
	MovieSearchParamGenre     MovieSearchParam = "genre"
	MovieSearchParamDoubanId  MovieSearchParam = "doubanId"
	MovieSearchParamYear      MovieSearchParam = "year"
)

// PossibleValuesForMovieSearchParam returns every value of MovieSearchParam.
func PossibleValuesForMovieSearchParam() []string {
	return []string{
		string(MovieSearchParamQ),
		string(MovieSearchParamImdbId),
		string(MovieSearchParamTmdbId),
		string(MovieSearchParamImdbTitle),
		string(MovieSearchParamImdbYear),
		string(MovieSearchParamTraktId),
		string(MovieSearchParamGenre),
		string(MovieSearchParamDoubanId),
		string(MovieSearchParamYear),
	}
}

// MusicSearchParam is the "MusicSearchParam" enum.
type MusicSearchParam string

// Values of MusicSearchParam.
const (
	MusicSearchParamQ      MusicSearchParam = "q"
	MusicSearchParamAlbum  MusicSearchParam = "album"
	MusicSearchParamArtist MusicSearchParam = "artist"
	MusicSearchParamLabel  MusicSearchParam = "label"
	MusicSearchParamYear   MusicSearchParam = "year"
	MusicSearchParamGenre  MusicSearchParam = "genre"
	MusicSearchParamTrack  MusicSearchParam = "track"
)

// PossibleValuesForMusicSearchParam returns every value of MusicSearchParam.
func PossibleValuesForMusicSearchParam() []string {
	return []string{
		string(MusicSearchParamQ),
		string(MusicSearchParamAlbum),
		string(MusicSearchParamArtist),
		string(MusicSearchParamLabel),
		string(MusicSearchParamYear),
		string(MusicSearchParamGenre),
		string(MusicSearchParamTrack),
	}
}

// SearchParam is the "SearchParam" enum.
type SearchParam string

// Values of SearchParam.
const (
	SearchParamQ SearchParam = "q"
)

// PossibleValuesForSearchParam returns every value of SearchParam.
func PossibleValuesForSearchParam() []string {
	return []string{
		string(SearchParamQ),
	}
}

// TvSearchParam is the "TvSearchParam" enum.
type TvSearchParam string

// Values of TvSearchParam.
const (
	TvSearchParamQ        TvSearchParam = "q"
	TvSearchParamSeason   TvSearchParam = "season"
	TvSearchParamEp       TvSearchParam = "ep"
	TvSearchParamImdbId   TvSearchParam = "imdbId"
	TvSearchParamTvdbId   TvSearchParam = "tvdbId"
	TvSearchParamRId      TvSearchParam = "rId"
	TvSearchParamTvMazeId TvSearchParam = "tvMazeId"
	TvSearchParamTraktId  TvSearchParam = "traktId"
	TvSearchParamTmdbId   TvSearchParam = "tmdbId"
	TvSearchParamDoubanId TvSearchParam = "doubanId"
	TvSearchParamGenre    TvSearchParam = "genre"
	TvSearchParamYear     TvSearchParam = "year"
)

// PossibleValuesForTvSearchParam returns every value of TvSearchParam.
func PossibleValuesForTvSearchParam() []string {
	return []string{
		string(TvSearchParamQ),
		string(TvSearchParamSeason),
		string(TvSearchParamEp),
		string(TvSearchParamImdbId),
		string(TvSearchParamTvdbId),
		string(TvSearchParamRId),
		string(TvSearchParamTvMazeId),
		string(TvSearchParamTraktId),
		string(TvSearchParamTmdbId),
		string(TvSearchParamDoubanId),
		string(TvSearchParamGenre),
		string(TvSearchParamYear),
	}
}
