// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetIndexerProxyByIdOperationResponse is the result of GetIndexerProxyById.
type GetIndexerProxyByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *IndexerProxyResource
}

// GetIndexerProxyById calls GET /api/v1/indexerproxy/{id}.
func (c Client) GetIndexerProxyById(ctx context.Context, id int) (result GetIndexerProxyByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v1/indexerproxy/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model IndexerProxyResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
