// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// LocalizationOption is the "LocalizationOption" schema.
type LocalizationOption struct {
	Name  string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
