// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetLocalizationOperationResponse is the result of GetLocalization.
type GetLocalizationOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetLocalization calls GET /api/v1/localization.
func (c Client) GetLocalization(ctx context.Context) (result GetLocalizationOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v1/localization",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
