// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

func TestOperationGetIndexerByIdNewznab(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/rss+xml", "file bytes")
	result, err := c.GetIndexerByIdNewznab(t.Context(), 7, GetIndexerByIdNewznabOperationOptions{
		T:          "v-T",
		Q:          "v-Q",
		Cat:        "v-Cat",
		Imdbid:     "v-Imdbid",
		Tmdbid:     7,
		Extended:   "v-Extended",
		Limit:      7,
		Offset:     7,
		Minage:     7,
		Maxage:     7,
		Minsize:    7,
		Maxsize:    7,
		Rid:        7,
		Tvmazeid:   7,
		Traktid:    7,
		Tvdbid:     7,
		Doubanid:   7,
		Season:     7,
		Ep:         "v-Ep",
		Album:      "v-Album",
		Artist:     "v-Artist",
		Label:      "v-Label",
		Track:      "v-Track",
		Year:       7,
		Genre:      "v-Genre",
		Author:     "v-Author",
		Title:      "v-Title",
		Publisher:  "v-Publisher",
		Configured: "v-Configured",
		Source:     "v-Source",
		Host:       "v-Host",
		Server:     "v-Server",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v1/indexer/7/newznab")
	expectQuery(t, r, "t", "v-T")
	expectQuery(t, r, "q", "v-Q")
	expectQuery(t, r, "cat", "v-Cat")
	expectQuery(t, r, "imdbid", "v-Imdbid")
	expectQuery(t, r, "tmdbid", "7")
	expectQuery(t, r, "extended", "v-Extended")
	expectQuery(t, r, "limit", "7")
	expectQuery(t, r, "offset", "7")
	expectQuery(t, r, "minage", "7")
	expectQuery(t, r, "maxage", "7")
	expectQuery(t, r, "minsize", "7")
	expectQuery(t, r, "maxsize", "7")
	expectQuery(t, r, "rid", "7")
	expectQuery(t, r, "tvmazeid", "7")
	expectQuery(t, r, "traktid", "7")
	expectQuery(t, r, "tvdbid", "7")
	expectQuery(t, r, "doubanid", "7")
	expectQuery(t, r, "season", "7")
	expectQuery(t, r, "ep", "v-Ep")
	expectQuery(t, r, "album", "v-Album")
	expectQuery(t, r, "artist", "v-Artist")
	expectQuery(t, r, "label", "v-Label")
	expectQuery(t, r, "track", "v-Track")
	expectQuery(t, r, "year", "7")
	expectQuery(t, r, "genre", "v-Genre")
	expectQuery(t, r, "author", "v-Author")
	expectQuery(t, r, "title", "v-Title")
	expectQuery(t, r, "publisher", "v-Publisher")
	expectQuery(t, r, "configured", "v-Configured")
	expectQuery(t, r, "source", "v-Source")
	expectQuery(t, r, "host", "v-Host")
	expectQuery(t, r, "server", "v-Server")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetIndexerByIdNewznab(t.Context(), 7, GetIndexerByIdNewznabOperationOptions{
		T:          "v-T",
		Q:          "v-Q",
		Cat:        "v-Cat",
		Imdbid:     "v-Imdbid",
		Tmdbid:     7,
		Extended:   "v-Extended",
		Limit:      7,
		Offset:     7,
		Minage:     7,
		Maxage:     7,
		Minsize:    7,
		Maxsize:    7,
		Rid:        7,
		Tvmazeid:   7,
		Traktid:    7,
		Tvdbid:     7,
		Doubanid:   7,
		Season:     7,
		Ep:         "v-Ep",
		Album:      "v-Album",
		Artist:     "v-Artist",
		Label:      "v-Label",
		Track:      "v-Track",
		Year:       7,
		Genre:      "v-Genre",
		Author:     "v-Author",
		Title:      "v-Title",
		Publisher:  "v-Publisher",
		Configured: "v-Configured",
		Source:     "v-Source",
		Host:       "v-Host",
		Server:     "v-Server",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
