// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetIndexerByIdDownloadOperationResponse is the result of GetIndexerByIdDownload.
//
// The operation answers application/octet-stream, left unread in HttpResponse.Body, which
// the caller must close.
type GetIndexerByIdDownloadOperationResponse struct {
	HttpResponse *http.Response
}

// GetIndexerByIdDownloadOperationOptions holds the query and header parameters of GetIndexerByIdDownload.
type GetIndexerByIdDownloadOperationOptions struct {
	Link string
	File string
}

// ToHeaders returns the header parameters the options set.
func (o GetIndexerByIdDownloadOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetIndexerByIdDownloadOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Link != "" {
		out.Append("link", o.Link)
	}
	if o.File != "" {
		out.Append("file", o.File)
	}
	return &out
}

// GetIndexerByIdDownload calls GET /api/v1/indexer/{id}/download.
func (c Client) GetIndexerByIdDownload(ctx context.Context, id int, options GetIndexerByIdDownloadOperationOptions) (result GetIndexerByIdDownloadOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           fmt.Sprintf("/api/v1/indexer/%d/download", id),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
