// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetIndexerByIdNewznabOperationResponse is the result of GetIndexerByIdNewznab.
//
// The operation answers application/rss+xml, left unread in HttpResponse.Body, which
// the caller must close.
type GetIndexerByIdNewznabOperationResponse struct {
	HttpResponse *http.Response
}

// GetIndexerByIdNewznabOperationOptions holds the query and header parameters of GetIndexerByIdNewznab.
type GetIndexerByIdNewznabOperationOptions struct {
	T          string
	Q          string
	Cat        string
	Imdbid     string
	Tmdbid     int
	Extended   string
	Limit      int
	Offset     int
	Minage     int
	Maxage     int
	Minsize    int64
	Maxsize    int64
	Rid        int
	Tvmazeid   int
	Traktid    int
	Tvdbid     int
	Doubanid   int
	Season     int
	Ep         string
	Album      string
	Artist     string
	Label      string
	Track      string
	Year       int
	Genre      string
	Author     string
	Title      string
	Publisher  string
	Configured string
	Source     string
	Host       string
	Server     string
}

// ToHeaders returns the header parameters the options set.
func (o GetIndexerByIdNewznabOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetIndexerByIdNewznabOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.T != "" {
		out.Append("t", o.T)
	}
	if o.Q != "" {
		out.Append("q", o.Q)
	}
	if o.Cat != "" {
		out.Append("cat", o.Cat)
	}
	if o.Imdbid != "" {
		out.Append("imdbid", o.Imdbid)
	}
	if o.Tmdbid != 0 {
		out.Append("tmdbid", strconv.Itoa(o.Tmdbid))
	}
	if o.Extended != "" {
		out.Append("extended", o.Extended)
	}
	if o.Limit != 0 {
		out.Append("limit", strconv.Itoa(o.Limit))
	}
	if o.Offset != 0 {
		out.Append("offset", strconv.Itoa(o.Offset))
	}
	if o.Minage != 0 {
		out.Append("minage", strconv.Itoa(o.Minage))
	}
	if o.Maxage != 0 {
		out.Append("maxage", strconv.Itoa(o.Maxage))
	}
	if o.Minsize != 0 {
		out.Append("minsize", strconv.FormatInt(o.Minsize, 10))
	}
	if o.Maxsize != 0 {
		out.Append("maxsize", strconv.FormatInt(o.Maxsize, 10))
	}
	if o.Rid != 0 {
		out.Append("rid", strconv.Itoa(o.Rid))
	}
	if o.Tvmazeid != 0 {
		out.Append("tvmazeid", strconv.Itoa(o.Tvmazeid))
	}
	if o.Traktid != 0 {
		out.Append("traktid", strconv.Itoa(o.Traktid))
	}
	if o.Tvdbid != 0 {
		out.Append("tvdbid", strconv.Itoa(o.Tvdbid))
	}
	if o.Doubanid != 0 {
		out.Append("doubanid", strconv.Itoa(o.Doubanid))
	}
	if o.Season != 0 {
		out.Append("season", strconv.Itoa(o.Season))
	}
	if o.Ep != "" {
		out.Append("ep", o.Ep)
	}
	if o.Album != "" {
		out.Append("album", o.Album)
	}
	if o.Artist != "" {
		out.Append("artist", o.Artist)
	}
	if o.Label != "" {
		out.Append("label", o.Label)
	}
	if o.Track != "" {
		out.Append("track", o.Track)
	}
	if o.Year != 0 {
		out.Append("year", strconv.Itoa(o.Year))
	}
	if o.Genre != "" {
		out.Append("genre", o.Genre)
	}
	if o.Author != "" {
		out.Append("author", o.Author)
	}
	if o.Title != "" {
		out.Append("title", o.Title)
	}
	if o.Publisher != "" {
		out.Append("publisher", o.Publisher)
	}
	if o.Configured != "" {
		out.Append("configured", o.Configured)
	}
	if o.Source != "" {
		out.Append("source", o.Source)
	}
	if o.Host != "" {
		out.Append("host", o.Host)
	}
	if o.Server != "" {
		out.Append("server", o.Server)
	}
	return &out
}

// GetIndexerByIdNewznab calls GET /api/v1/indexer/{id}/newznab.
func (c Client) GetIndexerByIdNewznab(ctx context.Context, id int, options GetIndexerByIdNewznabOperationOptions) (result GetIndexerByIdNewznabOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           fmt.Sprintf("/api/v1/indexer/%d/newznab", id),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
