// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PostNotificationTestAllOperationResponse is the result of PostNotificationTestAll.
type PostNotificationTestAllOperationResponse struct {
	HttpResponse *http.Response
	Model        []ProviderTestAllResult
}

// PostNotificationTestAll calls POST /api/v1/notification/testall.
func (c Client) PostNotificationTestAll(ctx context.Context) (result PostNotificationTestAllOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
			http.StatusBadRequest,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v1/notification/testall",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
