// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// NotificationResource is the "NotificationResource" schema.
type NotificationResource struct {
	ConfigContract              string                 `json:"configContract,omitempty"`
	Fields                      []Field                `json:"fields,omitzero"`
	Id                          int                    `json:"id,omitempty"`
	Implementation              string                 `json:"implementation,omitempty"`
	ImplementationName          string                 `json:"implementationName,omitempty"`
	IncludeHealthWarnings       *bool                  `json:"includeHealthWarnings,omitempty"`
	IncludeManualGrabs          *bool                  `json:"includeManualGrabs,omitempty"`
	InfoLink                    string                 `json:"infoLink,omitempty"`
	Link                        string                 `json:"link,omitempty"`
	Message                     *ProviderMessage       `json:"message,omitempty"`
	Name                        string                 `json:"name,omitempty"`
	OnApplicationUpdate         *bool                  `json:"onApplicationUpdate,omitempty"`
	OnGrab                      *bool                  `json:"onGrab,omitempty"`
	OnHealthIssue               *bool                  `json:"onHealthIssue,omitempty"`
	OnHealthRestored            *bool                  `json:"onHealthRestored,omitempty"`
	Presets                     []NotificationResource `json:"presets,omitzero"`
	SupportsOnApplicationUpdate *bool                  `json:"supportsOnApplicationUpdate,omitempty"`
	SupportsOnGrab              *bool                  `json:"supportsOnGrab,omitempty"`
	SupportsOnHealthIssue       *bool                  `json:"supportsOnHealthIssue,omitempty"`
	SupportsOnHealthRestored    *bool                  `json:"supportsOnHealthRestored,omitempty"`
	Tags                        []int                  `json:"tags,omitzero"`
	TestCommand                 string                 `json:"testCommand,omitempty"`
}
