// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// GetSearchOperationResponse is the result of GetSearch.
type GetSearchOperationResponse struct {
	HttpResponse *http.Response
	Model        []ReleaseResource
}

// GetSearchOperationOptions holds the query and header parameters of GetSearch.
type GetSearchOperationOptions struct {
	Query      string
	Type       string
	IndexerIds []int
	Categories []int
	Limit      int
	Offset     int
}

// ToHeaders returns the header parameters the options set.
func (o GetSearchOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetSearchOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Query != "" {
		out.Append("query", o.Query)
	}
	if o.Type != "" {
		out.Append("type", o.Type)
	}
	for _, v := range o.IndexerIds {
		out.Append("indexerIds", strconv.Itoa(v))
	}
	for _, v := range o.Categories {
		out.Append("categories", strconv.Itoa(v))
	}
	if o.Limit != 0 {
		out.Append("limit", strconv.Itoa(o.Limit))
	}
	if o.Offset != 0 {
		out.Append("offset", strconv.Itoa(o.Offset))
	}
	return &out
}

// GetSearch calls GET /api/v1/search.
func (c Client) GetSearch(ctx context.Context, options GetSearchOperationOptions) (result GetSearchOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v1/search",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
