// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

func TestOperationGetSearch(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "[{}]")
	result, err := c.GetSearch(t.Context(), GetSearchOperationOptions{
		Query:      "v-Query",
		Type:       "v-Type",
		IndexerIds: []int{1, 2},
		Categories: []int{1, 2},
		Limit:      7,
		Offset:     7,
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v1/search")
	expectQuery(t, r, "query", "v-Query")
	expectQuery(t, r, "type", "v-Type")
	expectQuery(t, r, "indexerIds", "1", "2")
	expectQuery(t, r, "categories", "1", "2")
	expectQuery(t, r, "limit", "7")
	expectQuery(t, r, "offset", "7")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetSearch(t.Context(), GetSearchOperationOptions{
		Query:      "v-Query",
		Type:       "v-Type",
		IndexerIds: []int{1, 2},
		Categories: []int{1, 2},
		Limit:      7,
		Offset:     7,
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetSearch(t.Context(), GetSearchOperationOptions{
		Query:      "v-Query",
		Type:       "v-Type",
		IndexerIds: []int{1, 2},
		Categories: []int{1, 2},
		Limit:      7,
		Offset:     7,
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
