// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// ReleaseResource is the "ReleaseResource" schema.
type ReleaseResource struct {
	Age              int               `json:"age,omitempty"`
	AgeHours         float64           `json:"ageHours,omitempty"`
	AgeMinutes       float64           `json:"ageMinutes,omitempty"`
	Categories       []IndexerCategory `json:"categories,omitzero"`
	CommentUrl       string            `json:"commentUrl,omitempty"`
	DownloadClientId int               `json:"downloadClientId,omitempty"`
	DownloadUrl      string            `json:"downloadUrl,omitempty"`
	FileName         string            `json:"fileName,omitempty"`
	Files            int               `json:"files,omitempty"`
	Grabs            int               `json:"grabs,omitempty"`
	Guid             string            `json:"guid,omitempty"`
	Id               int               `json:"id,omitempty"`
	ImdbId           int               `json:"imdbId,omitempty"`
	Indexer          string            `json:"indexer,omitempty"`
	IndexerFlags     []string          `json:"indexerFlags,omitzero"`
	IndexerId        int               `json:"indexerId,omitempty"`
	InfoHash         string            `json:"infoHash,omitempty"`
	InfoUrl          string            `json:"infoUrl,omitempty"`
	Leechers         int               `json:"leechers,omitempty"`
	MagnetUrl        string            `json:"magnetUrl,omitempty"`
	PosterUrl        string            `json:"posterUrl,omitempty"`
	Protocol         DownloadProtocol  `json:"protocol,omitempty"`
	PublishDate      string            `json:"publishDate,omitempty"`
	ReleaseHash      string            `json:"releaseHash,omitempty"`
	Seeders          int               `json:"seeders,omitempty"`
	Size             int64             `json:"size,omitempty"`
	SortTitle        string            `json:"sortTitle,omitempty"`
	SubGroup         string            `json:"subGroup,omitempty"`
	Title            string            `json:"title,omitempty"`
	TmdbId           int               `json:"tmdbId,omitempty"`
	TvMazeId         int               `json:"tvMazeId,omitempty"`
	TvdbId           int               `json:"tvdbId,omitempty"`
}
