// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

import (
	"context"
	"net/http"

	"github.com/katbyte/prowlarr-mcp/lib/client"
)

// PostSearchBulkOperationResponse is the result of PostSearchBulk.
type PostSearchBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        []ReleaseResource
}

// PostSearchBulk calls POST /api/v1/search/bulk.
func (c Client) PostSearchBulk(ctx context.Context, input []ReleaseResource) (result PostSearchBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v1/search/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
