// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// TagResource is the "TagResource" schema.
type TagResource struct {
	Id    int    `json:"id,omitempty"`
	Label string `json:"label,omitempty"`
}
