// Code generated by internal/pandorest; DO NOT EDIT.

package prowlarr

// TagDetailsResource is the "TagDetailsResource" schema.
type TagDetailsResource struct {
	ApplicationIds  []int  `json:"applicationIds,omitzero"`
	Id              int    `json:"id,omitempty"`
	IndexerIds      []int  `json:"indexerIds,omitzero"`
	IndexerProxyIds []int  `json:"indexerProxyIds,omitzero"`
	Label           string `json:"label,omitempty"`
	NotificationIds []int  `json:"notificationIds,omitzero"`
}
